version: "3.7"

services:
  example-account-db:
    container_name: example-account-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: account
      POSTGRES_PASSWORD: pass123
